services:

  # Spin up the backend
  backend:
    image: surigo/anizenith_backend:latest
    container_name: anizenith_backend
    ports:
      - '22021:9002'
    networks:
      - anizenith_net
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9002/health']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 90s
    restart: unless-stopped


  # Spin up the frontend
  frontend:
    image: surigo/anizenith_frontend:latest
    container_name: anizenith_frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '22020:7002'
    networks:
      - anizenith_net
    restart: unless-stopped





  # TODO: Add this later
  # ngrok:
  #   image: ngrok/ngrok:latest
  #   container_name: ngrok
  #   depends_on:
  #     - frontend
  #   command: http frontend:7860
  #   environment:
  #     NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
  #   ports:
  #   - "22003:4040"
  #   networks:
  #     - cookiemancer_net
  #   restart: unless-stopped

  # TODO: Add this later
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker:/var/lib/docker:ro
  #     - /dev/disk:/dev/disk:ro
  #   networks:
  #     - cookiemancer_net
  #   restart: unless-stopped

  # TODO: Add this later
  # node-exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   container_name: node_exporter
  #   command:
  #     - --path.rootfs=/host
  #     - --path.procfs=/host/proc
  #     - --path.sysfs=/host/sys
  #     - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
  #   volumes:
  #     - /:/host:ro
  #   pid: host
  #   networks:
  #     - cookiemancer_net
  #   restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      # Map a volume from the local (to where compose.yml is run) prometheus.yml file to an internal container volume
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - '22023:9090'
    depends_on:
      - frontend
      - backend
      # TODO: Uncomment these once services are added
#      - cadvisor
#      - node-exporter
    networks:
      - anizenith_net
    restart: unless-stopped

  # TODO: Add this later
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "22005:3000"
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - cookiemancer_net
  #   restart: unless-stopped

networks:
  anizenith_net:
    driver: bridge

# Maps prometheus data to a volume outside the container (in case container is destroyed)
volumes:
   prometheus_data:
     driver: local
#   grafana_data:
#     driver: local
