# Define all services of the project
services:

  # "backend" service
  backend:
    image: surigo/anizenith_backend:latest
    container_name: anizenith_backend
    ports:
      - '22021:9002'
    networks:
      - anizenith_net

    # Calls the health check endpoint using defined configs before declaring the service as "Healthy"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9002/health']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 90s
    restart: unless-stopped


  # "frontend" service
  frontend:
    image: surigo/anizenith_frontend:latest
    container_name: anizenith_frontend

    # Waits for the "backend" service to be in the "service_healthy" status before startup
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '22020:7002'
    networks:
      - anizenith_net
    restart: unless-stopped

  # Spin up "cadvisor" as a service
  # This is responsible for collecting metrics on a container level (CPU / Memory / Network I/O)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    networks:
      - anizenith_net
    restart: unless-stopped

  # Spin up "node-exporter" as a service
  # This is resposible for collecting metrics on a node / hardware device level (Uptime / CPU / Memory / Network I/O)
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - --path.rootfs=/host
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    volumes:
      - /:/host:ro
    pid: host
    networks:
      - anizenith_net
    restart: unless-stopped

  # Spin up "prometheus" service
  # This will be scraping metrics from other services and hosting it in a DB
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      # Map a volume from the local (to where compose.yml is run) prometheus.yml file to an internal container volume
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - '22023:9090'
    depends_on:
      - frontend
      - backend
      - cadvisor
      - node-exporter
    networks:
      - anizenith_net
    restart: unless-stopped

  # Spin up "ngrok" service
  # This will be useful for creating secure tunnels to expose local development servers to the internet
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok

    # For now we are tunning frontend
    # TODO: Hookup grafana as well (maybe using ngrok.yml)
    depends_on:
      - frontend
    command: http frontend:7002
    ports:
      - "22022:4040"
    networks:
      - anizenith_net
    restart: unless-stopped
    env_file:
      - ngrok.env

  # Spin up "grafana" as a service
  # This will be used to Monitoring Dashboards using metrics data from Prometheus service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "22025:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - anizenith_net
    restart: unless-stopped

# Define custom bridge network which encapsulates all services defined above
networks:
  anizenith_net:
    driver: bridge

# Maps prometheus and grafana data to a volume outside the container (in case container is destroyed)
volumes:
   prometheus_data:
     driver: local
   grafana_data:
     driver: local
