global:
  # Grab from metrics endpoints every 15 seconds
  scrape_interval: 15s

scrape_configs:
  - job_name: 'frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['frontend:7002']

  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:9002']
