name: Sync to HuggingFace Spaces
on: 
  push:
    branches: [ "production" ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
          fetch-depth: 0
          lfs: true
      - name: Install xet
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/huggingface/xet-core/refs/heads/main/git_xet/install.sh | sh
          echo "$HOME/.xet/bin" >> $GITHUB_PATH
      - name: Set git user for xet security
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
      - name: Convert binaries to xet and Push to HuggingFace
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git xet init --force
          git xet track "*.db" "*.png" "*.jpg" "*.jpeg"

          git remote add huggingface "https://MLDevOps:$HF_TOKEN@huggingface.co/spaces/MLDevOps/CS553_CaseStudy1"
          git push huggingface production --force